[package]
name = "office-notice"
version = "0.1.1"
edition = "2024"

[dependencies]
log = "^0.4"
pretty_env_logger = "0.5"

testing = { git = "https://github.com/a-givertzman/rust-testing.git", tag = "0.1.2" }
debugging = { git = "https://github.com/a-givertzman/rust-debuging.git", tag = "0.0.1" }

tokio = { version =  "1.45", features = ["rt-multi-thread", "macros"] }
teloxide = { version = "0.15", features = ["macros"] }
openssl = { version = "0.10", features = ["vendored"] }

serde = { version = "^1.0", features = ["derive"] }
serde_yaml = "^0.9"
serde_json = "^1.0"


lazy_static = "^1.5"
once_cell = "1.17.1"
chrono = "^0.4"
futures = "^0.3"
strum = { version = "0.27.0", features = ["derive"] }
derive_more = { version = "^2.0", features = [ "from" ]}
arraylib = "^0.3"
reqwest = "^0.12"
indexmap = { version = "^2.2", features = ["serde"] }

[build]
rustflags = ["-Clinker=rust-lld"]
