services:
  office-notice-telegram-bot:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ../config.yaml:/bot/config.yaml
      - ../assets:/bot/assets